### PR TITLE
Implentation of Functions for the Use of Storage Objects

### PR DESCRIPTION
**Pull request by hedrickj19**
Contains methods for access and manipulating Storage Objects,
Contatins getter functions for the attributes of items,
Created many new Items

### CODE REVIEW

**Comment by skiadas** [comment]
@hedrickj19 Going to need to rebase your inventory branch onto master again, I can't merge them.

**Comment by hedrickj19** [comment]
It keeps saying rebase failed.

**Comment by skiadas** [comment]
Try from the command-line. The command would be (after you fetched all):

git rebase origin/master

**Comment by hedrickj19** [comment]
Ok. I think I was able to get the rebase to work, but it made duplicates of many of my commits when I was "resolving conflicts". That is why I know have multiple copies of several commits.

**Pull request closed without merging**
